### ISSUE TITLE
Error when authenticating with Figma account

### ISSUE THREAD

**Issue by TheHoltz** [HaikuTeam/animator#1056]
Hello everyone!

When I press the Figma button, I allow Haiku Animator to access Figma, and when I get redirected back to the application I'm getting a generic error, does anyone know how to fix it? I am currently using Macbook m1 in the lastest .dmg release.

<img width="339" alt="Captura de Tela 2021-10-08 às 18 55 52" src="https://user-images.githubusercontent.com/38303017/136628863-883fe896-3474-4176-8354-331e314e371e.png">

**Comment by ha7rock** [comment]
Same here...How can i fix it plz.

**Comment by pigeonflight** [comment]
Having the same issue. My current workaround is to export and import SVGs.

**Comment by KillDozerX2** [comment]
Same here

**Comment by gumptious** [comment]
This is resolved with the combination of 9621235c and https://github.com/HaikuTeam/figma-auth/

Figma OAuth requires an internet-accessible web service to perform token exchange. The default token exchange service was part of the commercial Haiku Animator offering and has been intentionally and permanently shut down.

https://github.com/HaikuTeam/figma-auth/ is a simple HTTP server that enables you to self-host a Figma OAuth token exchange service, while 9621235c enables specifying your own `FIGMA_CLIENT_ID` in the Haiku Animator app (and adds a more helpful error message.)

Read more at https://github.com/HaikuTeam/figma-auth/

**Comment by think1st** [comment]
The issue still persists (latest mac build), unable to use the app

**Comment by Akash187** [comment]
Still facing the same issue.

**Comment by raviavanigadda** [comment]
Still facing the issue.

**Comment by EdwinPalacio5** [comment]
Still facing the same issue.

**Comment by maximilliangeorge** [comment]
> This is resolved with the combination of [9621235](https://github.com/HaikuTeam/animator/commit/9621235c1cb24f1ca3c5ee4ca997f33887c27e6b) and https://github.com/HaikuTeam/figma-auth/
> 
> Figma OAuth requires an internet-accessible web service to perform token exchange. The default token exchange service was part of the commercial Haiku Animator offering and has been intentionally and permanently shut down.
> 
> https://github.com/HaikuTeam/figma-auth/ is a simple HTTP server that enables you to self-host a Figma OAuth token exchange service, while [9621235](https://github.com/HaikuTeam/animator/commit/9621235c1cb24f1ca3c5ee4ca997f33887c27e6b) enables specifying your own `FIGMA_CLIENT_ID` in the Haiku Animator app (and adds a more helpful error message.)
> 
> Read more at https://github.com/HaikuTeam/figma-auth/

I gave this a shot but the `figma-auth` binary doesn't seem to want to start. I was able to compile it, create an app to obtain an id + secret, but it just fails silently.

**Comment by codearis** [comment]
Well this is sad, same here.

**Comment by amireds** [comment]
Any solution to this yet please? Experiencing the same issues

**Comment by GameandDario** [comment]
Same here; have to export files svg which quite labourious doing this after every change in figma.

**Comment by gsaada** [comment]
Any solution?

**Comment by mlawrence22** [comment]
Any Solution?

**Comment by nova4u** [comment]
This crucial problem has not been fixed in one year? Is there any development going on? It literally makes this software unusable

**Comment by aitormendez** [comment]
Same problem here.

**Comment by dinbtechit** [comment]
experiencing the same problem. I see the issue has been closed.

**Comment by aitormendez** [comment]
The app is not in active development. There is 40 open issues and last commit is from a year ago.  Read this:

https://github.com/HaikuTeam/animator#status-of-this-project

**Comment by Janicesiau** [comment]
same here ! :((((

**Comment by SebastianKumor** [comment]
This is an issue still, not sure why is it closed. Seems like project is not maintained anymore.

**Comment by MuhammadAarfeen** [comment]
Still facing this issue on the latest Mac with apple silicon.
